version: "3.8"

services:
  bitcoin-node:
    build:
      context: .
      dockerfile: dockerfile
    container_name: bitcoin-node
    restart: always
    network_mode: "host"
    volumes:
      - ./data:/root/.bitcoin # Mount the repository directory as a volume
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["-printtoconsole", "-conf=/bitcoin/bitcoin.conf"]
