version: "3.8"

services:
  bitcoin-node:
    build:
      context: .
      dockerfile: dockerfile
    container_name: bitcoin-node
    network_mode: "host"
    volumes:
      - .:/root/.bitcoind # Mount the repository directory as a volume
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["-printtoconsole", "-conf=/root/.bitcoind/bitcoin.conf"]
